# MPLAB IDE generated this makefile for use with GNU make.
# Project: MULTIPLEXANDO.mcp
# Date: Mon Nov 02 14:17:23 2009

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

multiplexando_copy.cof : multiplexando_copy.o
	$(LD) /p16F84A "multiplexando_copy.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"multiplexando_copy.cof" /M"multiplexando_copy.map" /W /x

multiplexando_copy.o : multiplexando_copy.asm C:/Archivos\ de\ programa/Microchip/MPASM\ Suite/P16F84A.INC
	$(AS) /q /p16F84A "multiplexando_copy.asm" /l"multiplexando_copy.lst" /e"multiplexando_copy.err" /d__DEBUG=1

clean : 
	$(RM) "multiplexando_copy.o" "multiplexando_copy.hex" "multiplexando_copy.err" "multiplexando_copy.lst" "multiplexando_copy.cof"

